version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
    - DB_URL=${DB_URL}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: golang
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: